[tool.poetry]
name = "dictionary"
version = "0.1.0"
description = ""
authors = ["Артем Кондратенко <artem-osteo@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
